name: 'Lint Setup'
description: 'Common setup steps for Lint jobs'
inputs:
  mergedSha:
    description: 'Merged SHA'
    required: true
  targetSha:
    description: 'Target SHA'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check if the PR can be merged and checkout the merge commit
      uses: ./.github/actions/get-merge-commit
      with:
        mergedSha: ${{ inputs.mergedSha }}
        merged-as-untrusted: true
        targetSha: ${{ inputs.targetSha }}
        target-as-trusted: ${{ inputs.targetSha != '' }}

    - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
      with:
        extra_nix_config: sandbox = true
